version: "3.7"
services:
    nginx:
      container_name: local_nginx
      build:
        context: ./localNginx #ローカル開発用です。HTTPSポートは公開しません 
        dockerfile: Dockerfile
      ports:
          - target: 80
            published: 8080
            protocol: tcp
    backend:
      container_name: local_backend
      init: true
      build:
        context: ../development/backend
        dockerfile: Dockerfile
    frontend:
      container_name: local_frontend
      build:
        context: ./dummyFrontend #dummyFrontendはダミーのhtmlのみ返却します。
        dockerfile: Dockerfile
    mysql:
      container_name: local_mysql
      build:
        context: ./localMysql
        dockerfile: Dockerfile
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
        MYSQL_DATABASE: "app"
        MYSQL_USER: "backend"
        MYSQL_PASSWORD : "backend"
